name: CI + CD

on:
  push:
    branches:
      - main

jobs:
  build-dev:
    name: build-dev
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running dev build"

  deploy-dev:
    name: deploy-dev
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: development
      url: https://foo.dev.yahoo.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to development"

  build-prod:
    name: build-prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running prod build"

  deploy-prod:
    name: deploy-prod
    runs-on: ubuntu-latest
    needs: build-prod
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to production"
