name: CI + CD

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-pr:
    name: deploy-pr
    runs-on: ubuntu-latest
    environment:
      name: pull_request
      url: "https://pr-${{ github.event.pull_request.number }}.foo.example.com"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running pr build"
          echo "${{ github.event.pull_request.number }}"
      - name: Deploy
        shell: bash
        run: |
          echo "running deploy"
