name: CI + CD

on:
  workflow_dispatch:

jobs:
  DeployProd:
    name: Deploy Prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://example.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Production
        shell: bash
        run: |
          echo "Deploying Production"
