name: CI + CD

on:
  pull_request:
    branches:
      - main

jobs:
  build-devel:
    name: build
    runs-on: ubuntu-latest
    environment:
      name: pull-request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running pr build"
          echo "${{ github.event.pull_request.number }}"

  development:
    name: development
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to development"

  build-prod:
    name: build
    runs-on: ubuntu-latest
    needs: development
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running prod build"

  production:
    name: production
    runs-on: ubuntu-latest
    needs: build-prod
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to production"
