name: CI + CD

on:
  push:
    branches:
      - main

jobs:
  build-devel:
    name: build-devel
    runs-on: ubuntu-latest
    environment:
      name: pull-request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running dev build"

  development:
    name: development
    runs-on: ubuntu-latest
    needs: build-devel
    environment:
      name: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to development"

  build-prod:
    name: build
    runs-on: ubuntu-latest
    needs: development
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "running prod build"

  production:
    name: production
    runs-on: ubuntu-latest
    needs: build-prod
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          echo "deploying to production"
