name: CI + CD

on:
  pull_request:
    branches:
      - main

jobs:
  DeployProd:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Production
        shell: bash
        run: |
          echo "Deploying Production"
          echo "${{ github.event.pull_request.number }}"
