name: terragrunt

on:
    workflow_call:
        inputs:
            appname:
                type: string
                required: true
                description: 'The name of the application'
    
jobs:
    terragrunt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Print App Name
              shell: bash
              run: |
                echo "App Name: ${{ inputs.appname }}"
            - name: Print Event Type
              shell: bash
              run: |
                echo "Event Type: ${{ github.event_name }}"