name: docker-meta

on:
    workflow_dispatch:
        inputs:
            ref:
                type: string
                required: true
                description: 'ref'
    
jobs:
    promote:
        name: Promote Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.tag }}
            - name: Docker Metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ github.repository }}
            - name: Output
              id: output
              run: |
                  echo "${{ steps.meta.outputs.labels }}"
                  echo "${{ steps.meta.outputs.tags }}"
                  
