name: docker-meta

on:
    workflow_dispatch:
        inputs:
            ref:
                type: string
                default: 'main'
                required: false
                description: 'ref'

jobs:
    promote:
        name: Promote Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.ref }}
            - name: Docker Metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ github.repository }}
                  tags: |
                    type=raw,value=sha-${{ github.event.inputs.ref }},priority=1001
                    type=ref,event=branch
                    type=ref,event=pr
                    type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            - name: Output
              id: output
              run: |
                  echo "${{ steps.meta.outputs.tags }}"
